server.port: 8087

logging:
  level:
    web: DEBUG

application:
  title: Case Sync Service
  version: 1.0

server:
  servlet:
    context-path: /case-sync-service


client:
  baseURL:
    caseStatusClient: http://localhost:8093/case-status-service

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfigurationD

paths:
  skip:
    - /actuator
    - /swagger
    - /api-docs/**

scheduler:
  schedulingEnabled: true
  time: 0 * * * * *
  user: systemuser

sync:
  caseType: ZLSS
  rootCategory:
  fromStatus: 05
  toStatus: 06
  noOfDays: 30